spring:
  application.name:
    sol_test
  cloud:
    function:
      definition: nonDurableQueue;exclusiveDurableQueue;consumerGroup;ConcurrentConsumerGroup;consumingHeader;PublishHeader;wildcardSubscribe;publishEventOnDynamicTopic;bindingHeader;bulkPublish;bulkConsume
                ;clientAck;bindingSpecificError;globalGenericError;bindingErrorHandler;globalErrorHandler
    stream:
      default:
        error-handler-definition: globalErrorHandler
#        supplier polls every configured time duration and triggers the supplier. By default, it polls every second
      poller:
        fixed-delay: 1000000
      bindings:
#      binder will actually create a nonDurable Queue
        nonDurableQueue-in-0:
          destination: spring/cloud/stream
#       binder will actually create a Durable Exclusive Queue
        exclusiveDurableQueue-in-0:
          destination: spring/cloud/stream/excl/durable
          group: exclusive
#       binder will actually create a Durable Non-Exclusive Queue
        consumerGroup-in-0:
          destination: spring/cloud/stream/consumerGroup
          group: nonexclusive
        ConcurrentConsumerGroup-in-0:
          destination: spring/cloud/stream/consumerGroup/concurrent
          group: nonexclusive
          consumer:
            concurrency: 5
#        Consuming  header from message
        consumingHeader-in-0:
          destination: spring/cloud/stream/consumerGroup/concurrent/header
          group: nonexclusive
          consumer:
            concurrency: 5
#        Publishing Header in Event
        PublishHeader-out-0:
          destination: spring/cloud/stream/consumerGroup/concurrent/header
#        Wildcard subscription.
        wildcardSubscribe-in-0:
          destination: 'spring/*/stream/>'
          group: nonexclusive
          consumer:
            concurrency: 5
        additionalQueueSubscription-in-0:
          destination: spring/cloud/stream/additional
          group: nonexclusive
          consumer:
            concurrency: 5
#        dynamic publishing
        publishEventOnDynamicTopic-in-0:
          destination: spring/cloud/stream/dynamic_publishing
          group: nonexclusive
          consumer:
            concurrency: 5
#      dynamic publishing with BinderHeaders.TARGET_DESTINATION
        bindingHeader-in-0:
          destination: spring/cloud/stream/dynamic_publishing/bindingHeader
          group: nonexclusive
          consumer:
            concurrency: 5
        bindingHeader-out-0:
          destination: 'my/default/topic'
#       Bulk event publishing
        bulkPublish-in-0:
          destination: 'abc/bulk/>'
          group: nonexclusive
          consumer:
            concurrency: 5
        bulkPublish-out-0:
          destination: 'my/default/topic'
#        Batch consume
        bulkConsume-in-0:
          destination: 'my/default/topic'
          group: batch
          consumer:
            batch-mode: true
            useNativeDecoding: true
#        Manual Acknowledgement
        clientAck-in-0:
          destination: 'a/b/>'
          group: clientAck
        clientAck:out-0:
          destination: 'my/default/topic'
#        Consumer Error Handling
        bindingSpecificError-in-0:
          destination: 'bindingSpecificError'
          group: clientAck
          error-handler-definition: bindingErrorHandler
          consumer:
            max-attempts: 2
            back-off-initial-interval: 1
            back-off-multiplier: 3
            default-retryable: true
            retryable-exceptions:
              java.lang.IllegalStateException: true
          binder: solace-broker

        globalGenericError-in-0:
          destination: 'globalGenericError'
          group: clientAck
          consumer:
            max-attempts: 2
            back-off-initial-interval: 1
            back-off-multiplier: 3
            default-retryable: true
            retryable-exceptions:
              java.lang.IllegalStateException: true
          binder: solace-broker
#       Solace specific property queueAccessType to use an exclusive queue.
      solace:
        bindings:
          exclusiveDurableQueue-in-0:
            consumer:
              queue-access-type:1 #1 is exclusive, 0 is nonExclusive
          additionalQueueSubscription-in-0:
            consumer:
              queueAdditionalSubscriptions:
                - 'spring/cloud/stream/additional/a'
                - 'spring/cloud/stream/additional/b'
#          Batch consume
          bulkConsume-in-0:
            consumer:
              batch-max-size: 5
              batch-timeout: 5000
#          Manual Acknowledgement
          clientAck-in-0:
            consumer:
              queueMaxMsgRedelivery: 2

      binders:
        #This section of the configuration tells the solace binder how to connect to the solace event broker/mesh
        solace-broker:
          type: solace
          environment:
            solace:
              java:
                host: tcps://mr-connection-61vipbi3itd.messaging.solace.cloud:55443
                msgVpn: solace_servive
                clientUsername: solace-cloud-client
                clientPassword: oghef03v4oj50sksdnj68p5mmj


